### ISSUE TITLE
Why not publish?

### ISSUE THREAD

**Issue by tomek-he-him** [fredcy/localstorage#1]
Hey @fredcy,

thanks a lot for this awesome lib. The API feels natural, the docs are good, the example is very helpful. The only painful thing was installation. I admit that both suggested ways to install do feel a bit hacky.

Just wondering – why not publish this to package.elm-lang.org?

**Comment by fredcy** [comment]
The package contains "native" code and so it can't be published unless Evan first whitelists it. I asked for approval or, alternatively, to have Evan and the core team take it for themselves. Nothing has come of that. Evan is writing his own localstorage package at https://github.com/elm-lang/local-storage

**Comment by tomek-he-him** [comment]
👍  Thanks for the clarification!

**Comment by quadrupleslap** [comment]
Man this walled-gardening is getting a bit frustrating.
