### ISSUE TITLE
Tag a release to work with elm-github-install

### ISSUE THREAD

**Issue by pisys** [fredcy/localstorage#6]
elm-install cannot satisfy my dependency since there are no tags in this repo. 

    ...
    "dependencies": {
            "fredcy/localstorage" : "1.0.0 <= v < 2.0.0"
    },
    "dependency-sources" : {
        "fredcy/localstorage" : "https://github.com/fredcy/localstorage"
    },
    ...

results in error by elm-install:

      Unable to satisfy the following requirements:
  
      - `https://github.com/fredcy/localstorage (< 2.0.0)` required by `user-specified dependency`
      - `https://github.com/fredcy/localstorage (>= 1.0.0)` required by `user-specified dependency`

**Comment by fredcy** [comment]
I just pushed a 1.0.0 tag on the latest commit on the master branch. Does that give you what you need?

**Comment by pisys** [comment]
Yes, that's it. Thx!
